namespace EmitToolbox.Framework;

/// <summary>
/// Content generated by proxy generator will be marked with this attribute.
/// </summary>
[AttributeUsage(AttributeTargets.All)]
public class GeneratedAttribute : Attribute
{}